import prisma from '@/lib/db';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Blog | Post',
	description: 'Generated by create next app',
};

export default async function Page({ params }: { params: { id: string } }) {
	const post = await prisma.post.findUnique({
		where: { id: parseInt(params.id) },
	});

	if (!post) {
		notFound();
	}

	return (
		<main className='text-center pt-24 px-7'>
			<h1 className='text-5xl font-semibold mb-7 '>{post.title}</h1>
			<p className='max-w-[700px] mx-auto'>{post.body}</p>
		</main>
	);
}
