import PostsList from '@/components/PostsList';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Blog | All Posts',
	description: 'Generated by create next app',
};

export default async function Page() {
	return (
		<main className='text-center pt-16 px-5'>
			<h1 className='text-4xl md:text-5xl font-bold mb-5'>All posts</h1>

			<Suspense fallback='loading...s'>
				<PostsList />
			</Suspense>
		</main>
	);
}
